config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :members, except: :show

  root "members#index"

  get "list" => "members#list"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/member.rb
class Member < ActiveRecord::Base

	validates :name, presence: :true, uniqueness: :true
	validates :title, presence: :true
	validates :sort, presence: :true

	has_attached_file :photo
	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	before_action :set_member, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_admin!, except: [:index]


	def index
		@members = Member.all
	end

	def list
		@members = Member.all
	end

	def show
	end

	def edit
	end

	def new
		@member = Member.new
	end

	def create
		@member = Member.new(member_params)
		if @member.save
			redirect_to list_path
			flash[:success] = "New member, #{@member.name} has been successfully created."
		else
			render 'new'
		end
	end

	def update
		if @member.update(member_params)
			redirect_to list_path
			flash[:success] = "#{@member.name} has been successully updated."
		else
			render 'edit'
		end
	end

	def destroy
		@member.destroy
		redirect_to list_url
	end

	private 

		def set_member
			@member = Member.find(params[:id])
		end

		def member_params
			params.require(:member).permit(:name, :title, :sort, :photo)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> alert-dismissible fade in" ><%= message %>
  	<button type="button" class="close" data-dismiss="alert">
	  <span aria-hidden="true">&times;</span>
	  <span class="sr-only">Close</span>
	</button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container text-center">
		<p>American College of Healthcare Executives Copyright &copy; 2014</p>
		<% if admin_signed_in? %>
			<div class="btn-group">
				<%= link_to "Sort List", root_path, class: "btn btn-footer btn-sm" %>
				<%= link_to "Member List", list_path, class: "btn btn-footer btn-sm" %>
				<%= link_to "Log out", destroy_admin_session_path, method: :delete, class: "btn btn-footer btn-sm" %>
			</div>
		<% else %>
				<%= link_to "Admin", list_path, class: "btn btn-footer btn-sm" %>
		<% end %>
	</div>
</footer>

app/views/layouts/_liladmin.html.erb
<div class="light-blue-header visible-xs-block visible-sm-block" data-spy="affix" id="sorter">
	<div class='container'>
		<h1 class="pull-left visible-sm-block">Board of Governors Exam</h1>
		<div class="pull-right">
			<div class="btn-group" style="margin-right:25px;">
			    <%= link_to new_member_path do %>
      				<button type="button" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus"></span> New Member</button>
   			    <% end %>
   			    <%= link_to root_path do %>
      				<button type="button" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-th-list"></span> Sort List</button>
   			    <% end %>
			</div>
			<div class="btn-group">
			  <button type="button" class="btn btn-dark btn-sm dropdown-toggle" data-toggle="dropdown">
			    <strong style="color:#ffffff;"><span class="glyphicon glyphicon-user"></span></strong>
			  </button>
				<ul class="dropdown-menu dropdown-menu-right" role="menu">
				    <li><%= link_to "Admin", list_path %></li>
				    <li><%= link_to "Edit Admin", edit_admin_registration_path %></li>
				    <li><%= link_to "Log out", destroy_admin_session_path, method: :delete %></li>
			    </ul>
			</div>	
		</div>
	</div>
</div>

app/views/layouts/_lilnav.html.erb
<div class="lilnav visible-xs-block visibile-sm-block" style="padding-top:50px;">
	<div class="btn-group-vertical visible-xs-block visibile-sm-block" role="group" aria-label="Mobile Nav Index" style="margin:10px 0;">
		<button type="button" class="btn btn-dark pop filter sort" data-sort="random" data-toggle="tooltip" data-placement="left" title="Shuffle"><span class="glyphicon glyphicon-refresh"></span></button>
		<button type="button" class="btn btn-dark tint"><span class="glyphicon glyphicon-adjust"></span></button>
	</div>

	<div class="btn-group-vertical visible-xs-block visibile-sm-block" role="group" aria-label="Mobile Nav Index">
		<button type="button" data-filter="all" class="btn btn-dark active filter"><span class="glyphicon glyphicon-th-list"></span></button>
		<button type="button" data-filter=".chair" class="btn btn-dark filter"><span class="glyphicon glyphicon-th-large"></span></button>
		<button type="button" data-filter=".gov" class="btn btn-dark filter"><span class="glyphicon glyphicon-th"></span></button>
	</div>
</div>

app/views/layouts/_sort_nav.html.erb
<div class="blue-head">
	<div class="container">
		<%= image_tag "logo.png" %>
	</div>
</div>
	<div class="light-blue-header hidden-xs hidden-sm" data-spy="affix" id="sorter">
		<div class='container'>
			<h1 class="pull-left">Board of Governors Exam</h1>
			<div class="pull-right">
			 <% if admin_signed_in? && !current_page?(root_path) %>
				<div class="btn-group" style="margin-right:25px;">
				    <%= link_to new_member_path do %>
	      				<button type="button" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> New Member</button>
	   			    <% end %>
	   			    <%= link_to root_path do %>
	      				<button type="button" class="btn btn-success"><span class="glyphicon glyphicon-th-list"></span> Sort List</button>
	   			    <% end %>
				</div>
				<div class="btn-group">
				  <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown">
				    Signed in as <strong style="color:#ffffff;">Admin</strong> <span class="caret"></span>
				  </button>
					<ul class="dropdown-menu" role="menu">
					    <li><%= link_to "Admin", list_path %></li>
					    <li><%= link_to "Edit Admin", edit_admin_registration_path %></li>
					    <li><%= link_to "Log out", destroy_admin_session_path, method: :delete %></li>
				    </ul>
				</div>
			<% else %>
				<button type="button" class="btn btn-default pop shuffle filter sort" data-sort="random" data-toggle="tooltip" data-placement="left" title="Shuffle"><span class="glyphicon glyphicon-refresh"></span></button>
				<div class="btn-group" data-toggle="buttons" style="margin-right:25px;">
					  <label class="btn btn-dark active tint">
					    <input type="radio" name="options" id="option2" autocomplete="off"> Color</label>
					  <label class="btn btn-dark tint">
					    <input type="radio" name="options" id="option3" autocomplete="off"> Grey</label>
				</div>
				<div class="btn-group">
					<button type="button" data-filter="all" class="btn btn-dark active filter">All</button>
					<button type="button" data-filter=".chair" class="btn btn-dark filter">Chairman</button>
					<button type="button" data-filter=".gov" class="btn btn-dark filter">Board</button>
				</div>
			<% end %>	
			</div>
		</div>
    </div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Boardprep2</title>
	  <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
<body>

<script>
	$(function(){
		$("#container").mixItUp(); 
		$(".pop").tooltip();
			$(".poop").popover();
		$(".tint").click(function () {
		   $(".darker").toggleClass("desaturate");
		  });
		$('#sorter, .lilnav').affix({
		    offset: {
		        top: 125
		    }
		});
	});
</script>	


<%= render "layouts/sort_nav" %>
<% if admin_signed_in? && !current_page?(root_path) %>
	<%= render "layouts/liladmin" %>
<% end %>

	<div class="container">
		<div clas="row">
			<%= render "layouts/flash" %>
			<%= yield %>
		</div>
	</div>
	<%= render "layouts/footer" %>

</body>
</html>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> alert-dismissible fade in" ><%= message %>
  	<button type="button" class="close" data-dismiss="alert">
	  <span aria-hidden="true">&times;</span>
	  <span class="sr-only">Close</span>
	</button>
  </div>
<% end %>

app/views/members/_form.html.erb
<div class="row form_top">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @member, html: { multipart: true } do |f| %>
			<% if @member.errors.any? %>
			  <div id="error_explanation">
			    <div class="alert alert-danger">
			      <h2>The form contains <%= pluralize(@member.errors.count, "error") %>.</h2>
				    <ul>
					    <% @member.errors.full_messages.each do |msg| %>
					      <li><%= msg %></li>
					    <% end %>
				    </ul>
				</div>
			  </div>
			<% end %>

				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, placeholder: "Enter Full Name and Credentials", class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :title %>
					<%= f.text_field :title, placeholder: "Enter ACHE Title", class: "form-control" %>
				</div>

				<div class="form-group">
					<%= f.label :sort, "Sort by" %>
					<%= f.select(:sort, options_for_select([["Chairman", "chair"],["Governors", "gov"]])) %>
						<div class="form-group pull-right">
							<%= f.file_field :photo, class: "btn btn-default" %>
						</div><br><br>
				</div>		
					<hr>
				<div class="form-group">
					<%= f.submit class: "btn btn-success" %> <%= link_to "Cancel", list_path, class: "btn btn-default btn-xs" %>
				</div>
		
		<% end %>
	</div>
</div>

app/views/members/_liladmin.html.erb
	<div class="blue-head">
		<div class="container">
			<%= image_tag "logo.png"%>
		</div>
	</div>
	<div class="light-blue-header visible-xs-block visible-sm-block" data-spy="affix" id="sorter">
		<div class='container'>
			<h1 class="pull-left">Board of Governors Exam</h1>
			<div class="pull-right">
				<div class="btn-group" style="margin-right:25px;">
				    <%= link_to new_member_path do %>
	      				<button type="button" class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> New Member</button>
	   			    <% end %>
	   			    <%= link_to root_path do %>
	      				<button type="button" class="btn btn-success"><span class="glyphicon glyphicon-th-list"></span> Sort List</button>
	   			    <% end %>
				</div>
				<div class="btn-group">
				  <button type="button" class="btn btn-dark dropdown-toggle" data-toggle="dropdown">
				    <strong style="color:#ffffff;"><span class="glyphicon glyphicon-user"></span></strong>
				  </button>
					<ul class="dropdown-menu" role="menu">
					    <li><%= link_to "Admin", list_path %></li>
					    <li><%= link_to "Edit Admin", edit_admin_registration_path %></li>
					    <li><%= link_to "Log out", destroy_admin_session_path, method: :delete %></li>
				    </ul>
				</div>	
			</div>
		</div>
    </div>

app/views/members/_lilnav.html.erb
<div class="lilnav visible-xs-block visibile-sm-block" style="padding-top:50px;">
	<div class="btn-group-vertical visible-xs-block visibile-sm-block" role="group" aria-label="Mobile Nav Index" style="margin:10px 0;">
		<button type="button" class="btn btn-dark pop filter sort" data-sort="random" data-toggle="tooltip" data-placement="left" title="Shuffle"><span class="glyphicon glyphicon-refresh"></span></button>
		<button type="button" class="btn btn-dark tint"><span class="glyphicon glyphicon-adjust"></span></button>
	</div>

	<div class="btn-group-vertical visible-xs-block visibile-sm-block" role="group" aria-label="Mobile Nav Index">
		<button type="button" data-filter="all" class="btn btn-dark active filter"><span class="glyphicon glyphicon-th-list"></span></button>
		<button type="button" data-filter=".chair" class="btn btn-dark filter"><span class="glyphicon glyphicon-th-large"></span></button>
		<button type="button" data-filter=".gov" class="btn btn-dark filter"><span class="glyphicon glyphicon-th"></span></button>
	</div>
</div>

app/views/members/edit.html.erb
<div class="row form_top">
	<div class="col-md-6 col-md-offset-3">
		<h1 class="text-center">Edit Board Member</h1>
		<hr>
	</div>
</div>
<%= render "form" %>

app/views/members/index.html.erb
<%= render "layouts/lilnav" %>
<div id="container" class="text-center">
	<% @members.each do |member| %>
		<div class="mix <%= "#{member.sort}" %>" style="margin:10px; cursor:pointer;">
			<%= image_tag member.photo.url, class: "poop img-rounded thumbnail darker img-responsive", data: { toggle: "popover", placement: "top", content: "#{member.title}", title: "#{member.name}"} %>
			<% if admin_signed_in? %>
				<div class="btn-group">
					<%= link_to "Edit", edit_member_path(member), class: "btn btn-default btn-sm" %>
					<%= link_to "Delete", member, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm" %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/members/list.html.erb
<h1>Members List</h1>
<div class="row">
	<div class="col-md-9">
		<div class="panel panel-default">
			<div id="better-tables">
				<table class="table table-striped table-condensed cf">	
					<thead class="cf">
						<tr>
							<th class="numeric">Photo</th>
							<th data-title="Name">Name</th>
							<th data-title="Title">Title</th>
							<th data-title="Sort">Sort</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @members.each do |member| %>
							<tr>
								<td style="padding-top:25px;"><%= image_tag member.photo.url, class: "thumbnail" %></td>
								<td style="padding-top:25px;"><strong><%= member.name %></strong></td>
								<td style="padding-top:25px;"><strong><%= member.title %></strong></td>
								<td style="padding-top:25px;"><strong><%= member.sort %></strong></td>
								<td style="padding-top:20px;">
									<div class="btn-group well well-sm">
										<%= link_to edit_member_path(member) do %>
											<button type="button" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-edit"></span> Edit</button>
										<% end %>
										<%= link_to member, method: :delete, data: { confirm: 'Are you sure?' } do %>
											<button type="button" class="btn btn-default btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</button>
										<% end %>
									</div>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
    </div>
    <div class="col-md-3">
    	<div class="panel panel-default">
    		<div class="panel-heading">
    			<h3 class="panel-title"><span class="glyphicon glyphicon-info-sign"></span> Heads-up</h3>
    		</div>
    		<div class="panel-body">
    			<p>When a new Board Member is added he/she will be shown on the <%= link_to "Sort List Page", root_path %> and in the table to the left. Any edits, updates or deletions will be reflected in both places.</p>
				<p>The list to left allows you to edit, update, delete and add new Board Members.</p>
				<hr>
                <p><strong>Note:</strong> If, after any activity in the admin area, you navigate to the home page and no images show up, simply refresh the page to fix it.</p>
    		</div>
    		<div class="panel-footer text-center">
    			<div class="btn-group">
                        <%= link_to new_member_path do %>
              				<button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> New Member</button>
           			    <% end %>
           			    <%= link_to root_path do %>
              				<button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-th-list"></span> Sort List</button>
           			    <% end %>
    		    </div>
    		</div>
    	</div>
    </div>
</div>

app/views/members/new.html.erb
<div class="row form_top">
	<div class="col-md-6 col-md-offset-3">
		<h1 class="text-center">Add New Board Member</h1>
		<hr>
	</div>
</div>
<%= render "form" %>